# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QGreenlandCustomizer
                                 A QGIS plugin
 QGreenland! Custom!
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-09
        copyright            : (C) 2021 by NSIDC
        email                : NSIDC@NSIDC.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QGreenlandCustomizer class from file QGreenlandCustomizer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .custom_qgreenland import QGreenlandCustomizer
    return QGreenlandCustomizer(iface)
